//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApolloAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApolloDatabaseEntities : DbContext
    {
        public ApolloDatabaseEntities()
            : base("name=ApolloDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Person> People { get; set; }
        public DbSet<Credential> Credentials { get; set; }
        public DbSet<Appointment> Appointments { get; set; }
        public DbSet<Discussion> Discussions { get; set; }
        public DbSet<Reply> Replies { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Avatar> Avatars { get; set; }
        public DbSet<Run> Runs { get; set; }
        public DbSet<Scoresheet> Scoresheets { get; set; }
        public DbSet<GameSystem> GameSystems { get; set; }
        public DbSet<Gym> Gyms { get; set; }
    }
}
