//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApolloAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public System.Guid Id { get; set; }
        public System.Guid DoctorId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime AppointmentTime { get; set; }
        public string Reason { get; set; }
        public bool IsApproved { get; set; }
    }
}
