//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApolloAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public System.Guid id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
    
        public virtual People_Doctor People_Doctor { get; set; }
        public virtual People_Trainer People_Trainer { get; set; }
        public virtual People_User People_User { get; set; }
        public virtual Credential Credential { get; set; }
    }
}
