//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApolloAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Run
    {
        public Run()
        {
            this.Routes = new HashSet<Route>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid RanBy { get; set; }
        public System.TimeSpan RunningTime { get; set; }
        public double Distance { get; set; }
        public int Point { get; set; }
    
        public virtual ICollection<Route> Routes { get; set; }
    }
}
